/*
 * Car mircro service
 * Micro service to book a car
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.carrental.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import org.bp.carrental.model.Car;
import org.bp.carrental.model.Parking;
import org.bp.carrental.model.PaymentCard;
import org.bp.carrental.model.Person;
/**
 * BookCarRentalRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-30T23:10:03.457+01:00[Europe/Belgrade]")
public class BookCarRentalRequest {
  @JsonProperty("person")
  private Person person = null;

  @JsonProperty("car")
  private Car car = null;

  @JsonProperty("parking")
  private Parking parking = null;

  @JsonProperty("paymentCard")
  private PaymentCard paymentCard = null;

  public BookCarRentalRequest person(Person person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/

  public Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public BookCarRentalRequest car(Car car) {
    this.car = car;
    return this;
  }

   /**
   * Get car
   * @return car
  **/

  public Car getCar() {
    return car;
  }

  public void setCar(Car car) {
    this.car = car;
  }

  public BookCarRentalRequest parking(Parking parking) {
    this.parking = parking;
    return this;
  }

   /**
   * Get parking
   * @return parking
  **/

  public Parking getParking() {
    return parking;
  }

  public void setParking(Parking parking) {
    this.parking = parking;
  }

  public BookCarRentalRequest paymentCard(PaymentCard paymentCard) {
    this.paymentCard = paymentCard;
    return this;
  }

   /**
   * Get paymentCard
   * @return paymentCard
  **/

  public PaymentCard getPaymentCard() {
    return paymentCard;
  }

  public void setPaymentCard(PaymentCard paymentCard) {
    this.paymentCard = paymentCard;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookCarRentalRequest bookCarRentalRequest = (BookCarRentalRequest) o;
    return Objects.equals(this.person, bookCarRentalRequest.person) &&
        Objects.equals(this.car, bookCarRentalRequest.car) &&
        Objects.equals(this.parking, bookCarRentalRequest.parking) &&
        Objects.equals(this.paymentCard, bookCarRentalRequest.paymentCard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, car, parking, paymentCard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookCarRentalRequest {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    car: ").append(toIndentedString(car)).append("\n");
    sb.append("    parking: ").append(toIndentedString(parking)).append("\n");
    sb.append("    paymentCard: ").append(toIndentedString(paymentCard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
