/*
 * Car mircro service
 * Micro service to book a car
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.carrental.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import org.bp.carrental.model.Parking;
import org.bp.carrental.model.Person;
/**
 * BookParkingRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-30T23:10:03.457+01:00[Europe/Belgrade]")
public class BookParkingRequest {
  @JsonProperty("person")
  private Person person = null;

  @JsonProperty("parking")
  private Parking parking = null;

  public BookParkingRequest person(Person person) {
    this.person = person;
    return this;
  }

   /**
   * Get person
   * @return person
  **/

  public Person getPerson() {
    return person;
  }

  public void setPerson(Person person) {
    this.person = person;
  }

  public BookParkingRequest parking(Parking parking) {
    this.parking = parking;
    return this;
  }

   /**
   * Get parking
   * @return parking
  **/

  public Parking getParking() {
    return parking;
  }

  public void setParking(Parking parking) {
    this.parking = parking;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookParkingRequest bookParkingRequest = (BookParkingRequest) o;
    return Objects.equals(this.person, bookParkingRequest.person) &&
        Objects.equals(this.parking, bookParkingRequest.parking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(person, parking);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookParkingRequest {\n");
    
    sb.append("    person: ").append(toIndentedString(person)).append("\n");
    sb.append("    parking: ").append(toIndentedString(parking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
