/*
 * Car mircro service
 * Micro service to book a car
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.carrental.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import org.bp.carrental.model.Point;
/**
 * Parking
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-11-30T23:10:03.457+01:00[Europe/Belgrade]")
public class Parking {
  @JsonProperty("from")
  private Point from = null;

  @JsonProperty("to")
  private Point to = null;

  public Parking from(Point from) {
    this.from = from;
    return this;
  }

   /**
   * Get from
   * @return from
  **/

  public Point getFrom() {
    return from;
  }

  public void setFrom(Point from) {
    this.from = from;
  }

  public Parking to(Point to) {
    this.to = to;
    return this;
  }

   /**
   * Get to
   * @return to
  **/

  public Point getTo() {
    return to;
  }

  public void setTo(Point to) {
    this.to = to;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Parking parking = (Parking) o;
    return Objects.equals(this.from, parking.from) &&
        Objects.equals(this.to, parking.to);
  }

  @Override
  public int hashCode() {
    return Objects.hash(from, to);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Parking {\n");
    
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
