version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka 
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  gateway:
    image: aznu/micro-carrental-booking
    ports:
      - "8090:8090"
    depends_on:
      - kafka
    environment:
      CARRENTAL_KAFKA_SERVER: kafka:9092
      CARRENTAL_SERVICE_TYPE: gateway
    volumes:
      - ./data:/app/data
  car:
    image: aznu/micro-carrental-booking
    depends_on:
      - kafka
    environment:
      CARRENTAL_KAFKA_SERVER: kafka:9092
      CARRENTAL_SERVICE_TYPE: car
    volumes:
      - ./data:/app/data
  parking:
    image: aznu/micro-carrental-booking
    depends_on:
      - kafka
    environment:
      CARRENTAL_KAFKA_SERVER: kafka:9092
      CARRENTAL_SERVICE_TYPE: parking
    volumes:
      - ./data:/app/data
  payment:
    image: aznu/micro-carrental-booking
    depends_on:
      - kafka
    environment:
      CARRENTAL_KAFKA_SERVER: kafka:9092
      CARRENTAL_SERVICE_TYPE: payment
    volumes:
      - ./data:/app/data
  flask_app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - gateway
    environment:
      - GATEWAY_URL=http://gateway:8090
    volumes:
      - ./data:/app/data
